### ISSUE TITLE
Cannot run console status (panic: runtinme error: index out of range)

### ISSUE THREAD

**Issue by atmo4th** [CPChain/chain#2]
I got an error when i tried to run status command (while cpchain node running)

**To Reproduce**
1. Sync cpchain node as per instructions on https://cpchain.io/community/?title=CPChain%20RNode%20Public%20Test%20Phase%20Starts%20from%204/29/2019
2. run  ./console-linux-amd status
3. got error message:

```
panic: runtime error: index out of range

goroutine 1 [running]:
bitbucket.org/cpchain/chain/tools/console/common.NewCpcClient(0xa5de11, 0x15, 0xc0000d6440, 0x20, 0xc0000af7a0, 0xf, 0x9bd2a0, 0x8, 0xc0000f98f8, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/common/client.go:32 +0x52b
bitbucket.org/cpchain/chain/tools/console/manager.NewConsole(0xc00009dd70, 0xa5de11, 0x15, 0xc0000d6440, 0x20, 0xc0000d6420, 0x1f, 0xc5b140, 0xc0000b0088, 0xc0000f9a98, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/manager/manager.go:52 +0xb1
main.build(0xc0000baf20, 0xc0000af6f4, 0xa3e8d8, 0x5, 0x4, 0xc0000a99d0, 0x5)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/flags.go:45 +0x263
main.showStatus(0xc0000baf20, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/cmd_status.go:20 +0x37
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.HandleAction(0x980420, 0xbb2de0, 0xc0000baf20, 0x0, 0xc0000b2de0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:501 +0xc8
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.Command.Run(0xa3ee79, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa6d470, 0x1b, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/command.go:165 +0x420
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.(*App).Run(0xc000158380, 0xc0000a6020, 0x2, 0x2, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:259 +0x6cf
main.main()
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/main.go:45 +0x4f
```

**Configuration**
 - OS: Ubuntu 19.04
 - cpchain version 0.2.3

**Comment by Liaojinlo** [comment]
use the following command:

`./console status --keystore ./datadir/keystore/YOUR_KEY_FILE --password ./datadir/password`

Here `YOUR_KEY_FILE` is the file generated previously in datadir/keystore/
