### ISSUE TITLE
Cannot retrieve node status from console

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#4]
**Where does the bug occur?**
Using console in linux terminal

**Describe the bug**
When i enter this command :

./console status --keystore datadir/keystore --password password

I get this error :

panic: runtime error: index out of range

goroutine 1 [running]:
bitbucket.org/cpchain/chain/tools/console/common.NewCpcClient(0xa5de11, 0x15, 0x7ffd243387a3, 0x10, 0xc0000997f0, 0xc, 0x9bd2a0, 0x8, 0xc0000e18f8, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/common/client.go:32 +0x52b
bitbucket.org/cpchain/chain/tools/console/manager.NewConsole(0xc000085d60, 0xa5de11, 0x15, 0x7ffd243387a3, 0x10, 0x7ffd243387bf, 0x8, 0xc5b140, 0xc00009c088, 0xc0000e1a98, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/manager/manager.go:52 +0xb1
main.build(0xc0000a51e0, 0xc000099763, 0xa3e8d8, 0x5, 0x4, 0xc00022a240, 0x5)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/flags.go:45 +0x263
main.showStatus(0xc0000a51e0, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/cmd_status.go:20 +0x37
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.HandleAction(0x980420, 0xbb2de0, 0xc0000a51e0, 0x0, 0xc00009ee40)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:501 +0xc8
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.Command.Run(0xa3ee79, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa6d470, 0x1b, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/command.go:165 +0x420
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.(*App).Run(0xc000134380, 0xc00009e120, 0x6, 0x6, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:259 +0x6cf
main.main()
        /ext-go/1/src/bitbucket.org/cpchain/chain/tools/console/main.go:45 +0x4f

**To Reproduce**
Exactly as described above

**Expected behavior**
I was expecting the status of the running node

**Screenshots**
none

** Configuration (please complete the following information):**
- CentOS 7 running on a VPS with 4Gb Ram / 256Gb Storage and 2 Cores

**Comment by siebeneicher** [comment]
The keystore file of your wallet should be added, e.g. like:

./console status --keystore datadir/keystore/UTC--2019-04-26T14-48-49.150481047Z--YOUR-WALLET --password ./password-file

**Comment by kbaf** [comment]
Yes! Thank you!
