### ISSUE TITLE
Authentication error after changing keystore file

### ISSUE THREAD

**Issue by brammb** [CPChain/chain#73]
Installed the software, created a new wallet, synced the blockchain.
After changed the keystore file with my keystore file from MEW which holds my CPC,
changed the wallet adress in the startup command and unlocked the wallet.
Then I get following error:

Unlocking account 0x15c9E31d6E713a50Ec037Edb5121c41B18eA7DE8 | Attempt 1/3
Password:
INFO[08-01|17:31:02.074] Unlocked account                              Line="cpchain/cmd_account.go:213" address=0x15c9E31d6E713a50Ec037Edb5121c41B18eA7DE8
INFO[08-01|17:31:02.122] start participating campaign                  Line="cpc/backend.go:414" campaign=true
INFO[08-01|17:31:02.122] Transaction pool price threshold updated      Line="core/tx_pool.go:579" price=18000000000
INFO[08-01|17:31:02.126] Starting mining operation                     Line="miner/miner.go:105"
goroutine 342 [running]:
bitbucket.org/cpchain/chain/consensus/dpor/backend.(*Handler).AddPeer(0xc0000bebb0, 0x1, 0xc0031a6300, 0x13863a0, 0xc002289b90, 0x6, 0x80, 0x1, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/handler.go:151 +0x1e4
bitbucket.org/cpchain/chain/protocols/cpc.(*ProtocolManager).handlePeer(0xc000095200, 0xc0031a6300, 0x13863a0, 0xc002289b90, 0x1, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/protocols/cpc/handler.go:341 +0x17a5
bitbucket.org/cpchain/chain/protocols/cpc.NewProtocolManager.func1(0xc0031a6300, 0x13863a0, 0xc002289b90, 0x2, 0x1)
        /ext-go/1/src/bitbucket.org/cpchain/chain/protocols/cpc/handler.go:124 +0x5b
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc002289b90, 0xc0031a6300, 0x13863a0, 0xc002289b90)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:353 +0x6d
created by bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:352 +0x20a

FATA[08-01|17:31:03.160] err when get message authentication code      Line="backend/handler.go:151" err="authentication needed: password or unlock"

I provide the correct password, the wallet unlocks, yet I get an error that authentication is needed.

**Comment by brammb** [comment]
I left the old keystore in the directory with .old extension. Once I deleted the old keystore it worked.
